name: Build RKE2 Cloud

on:
  push:
    branches:
      - prod

jobs:
  buildx:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build image 
        run: |
          echo "hi";
        