name: Build RKE2 Cloud

on:
  push:
    branches:
      - prod

jobs:
  buildx:
    runs-on: self-hosted
    env:
        TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
                
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform Backend
          id: backend
          run: |
            cat > backend.tf << EOF
            terraform { 
                cloud { 
                    organization = "${{ github.repository_owner }}"

                    workspaces { 
                        name = "k8s-cluster" 
                    } 
                } 
            }
            EOF

        - name: Manually Configure Terraform Credentials
          run: |
            mkdir -p .terraform.d
            cat <<EOF > .terraform.d/credentials.tfrc.json
            {
            "credentials": {
                "app.terraform.io": {
                "token": "${TF_API_TOKEN}"
                }
            }
            }
            EOF

        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: TF_LOG=DEBUG terraform init

        - name: teardown cluster
          run: |
                terraform destroy -auto-approve

        - name: setup cluster
          run: |
                sudo /bin/bash
                source /home/chris/.bashrc
                sudo ./setup.sh
        