name: Build RKE2 Cloud

on:
  push:
    branches:
      - prod

jobs:
  buildx:
    runs-on: self-hosted
    env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    steps:
        - name: Debug Secrets
          run: |
                echo "TF_API_TOKEN is set: ${TF_API_TOKEN:+yes}"
                
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform Backend
          id: backend
          run: |
            cat > backend.tf << EOF
            terraform { 
                cloud { 
                    organization = "${{ github.repository_owner }}"

                    workspaces { 
                        name = "k8s-cluster" 
                    } 
                } 
            }
            EOF
    
        - uses: hashicorp/setup-terraform@v3
          with:
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} 

        - name: Set Terraform Credentials
          run: |
                echo ${{ secrets.TF_API_TOKEN }} | terraform login

        - name: Terraform Init
          run: terraform init

        - name: teardown cluster
          run: |
                terraform destroy -auto-approve

        - name: setup cluster
          run: |
                sudo /bin/bash
                source /home/chris/.bashrc
                sudo ./setup.sh
        