name: Build RKE2 Cloud

on:
  push:
    branches:
      - prod

jobs:
  buildx:
    runs-on: self-hosted
    env:
        TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
                
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform Backend
          id: backend
          run: |
            cat > backend.tf << EOF
            terraform { 
                backend "remote" { 
                    organization = "${{ github.repository_owner }}"

                    workspaces { 
                        name = "k8s-cluster" 
                    } 
                } 
            }
            EOF

        - name: Manually Configure Terraform Credentials
          run: |
            mkdir -p .terraform.d
            mkdir -p ~/.terraform.d
            cat <<EOF > .terraform.d/credentials.tfrc.json
            {
            "credentials": {
                "app.terraform.io": {
                "token": "${TF_API_TOKEN}"
                }
            }
            }
            EOF
            cp .terraform.d/credentials.tfrc.json ~/.terraform.d/credentials.tfrc.json

        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: terraform init 

        - name: Start Libvirt Daemon
          run: sudo systemctl start libvirtd

        - name: Check Libvirt Status
          run: sudo systemctl status libvirtd   

        - name: teardown cluster
          run: |
                virsh -c qemu:///system list --all
                terraform destroy -auto-approve

        - name: Test Libvirt Access
          run: virsh -c qemu:///system list --all

        - name: terraform apply
          run: |
                    sudo -u $(whoami) virsh -c qemu:///system list --all
                    groups $(whoami)
                    virsh uri
                    virsh -c qemu:///session list
                    ls -al /var/run
                    ls -al /var/run/libvirt
                    terraform apply -auto-approve

        - name: setup cluster
          run: |
            
                echo $TF_API_TOKEN | terraform login app.terraform.io
                ./setup.sh
        