name: Build RKE2 Cloud

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: self-hosted  # Run directly on the host, NOT in a container

    env:
        TF_API_TOKEN: ${{ secrets.TFE_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform Backend
        run: |
          cat > backend.tf << EOF
          terraform { 
              backend "remote" { 
                  organization = "${{ github.repository_owner }}"
                  workspaces { 
                      name = "k8s-cluster" 
                  } 
              } 
          }
          EOF

      - name: Configure Terraform Credentials
        run: |
          mkdir -p ~/.terraform.d
          cat <<EOF > ~/.terraform.d/credentials.tfrc.json
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${TF_API_TOKEN}"
              }
            }
          }
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve

      - name: Start SSH Agent
        run: |
            eval $(ssh-agent -s)
            gpg-connect-agent updatestartuptty /bye
            gpgconf --list-options gpg-agent | grep enable-ssh-support
            export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
            ssh-add -L
  
      - name: Build cluster
        run: |
            terraform apply -auto-approve 
            sudo ./setup.sh

